# Generated by Django 4.2.1 on 2023-05-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('comment_reservation', models.CharField()),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.conferenceroom')),
            ],
            options={
                'unique_together': {('date_reservation', 'id_room')},
            },
        ),
    ]
